### ISSUE TITLE
'Close Table' command crashes on Thematic Layers

### ISSUE THREAD

**Issue by aharfoot** [PeterHorsbollMoller/mbWindowHelper#5]
If a Thematic layer is right clicked from the Layer Control window and the 'Close table' command is chosen, then the tool crashes and the following error is reported:

![WindowHelperError](https://f.cloud.github.com/assets/3789465/228422/e8498496-867f-11e2-9f5f-e6fcb9b36e19.png)

MapInfo 11.5.2, Win 7 x64

**Comment by PeterHorsbollMoller** [comment]
Thanks for reporting this bug, Andy.
I'll look into it once I get a few moment to spare

**Comment by PeterHorsbollMoller** [comment]
This issue is now fixed.
